In [5]:
import ensurepip
ensurepip.bootstrap()

In [8]:
import numpy as np

In [1]:
import pandas as pd
df = pd.read_csv("data_by_genres.csv")
df

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968,1,zolo,0.222625,0.547082,2.580991e+05,0.610240,0.143872,0.204206,-11.295878,0.061088,125.494919,0.596155,33.778943,9
2969,0,zouglou,0.161000,0.863000,2.063200e+05,0.909000,0.000000,0.108000,-5.985000,0.081300,119.038000,0.845000,58.000000,7
2970,1,zouk,0.263261,0.748889,3.060728e+05,0.622444,0.257227,0.089678,-10.289222,0.038778,101.965222,0.824111,46.666667,5
2971,0,zurich indie,0.993000,0.705667,1.984173e+05,0.172667,0.468633,0.179667,-11.453333,0.348667,91.278000,0.739000,0.000000,7
2972,1,zydeco,0.421038,0.629409,1.716717e+05,0.609369,0.019248,0.255877,-9.854825,0.050491,126.366087,0.808544,30.261905,7

In [11]:
df.head()

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7

In [12]:
df.tail()

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
2968,1,zolo,0.222625,0.547082,258099.064530,0.610240,0.143872,0.204206,-11.295878,0.061088,125.494919,0.596155,33.778943,9
2969,0,zouglou,0.161000,0.863000,206320.000000,0.909000,0.000000,0.108000,-5.985000,0.081300,119.038000,0.845000,58.000000,7
2970,1,zouk,0.263261,0.748889,306072.777778,0.622444,0.257227,0.089678,-10.289222,0.038778,101.965222,0.824111,46.666667,5
2971,0,zurich indie,0.993000,0.705667,198417.333333,0.172667,0.468633,0.179667,-11.453333,0.348667,91.278000,0.739000,0.000000,7
2972,1,zydeco,0.421038,0.629409,171671.690476,0.609369,0.019248,0.255877,-9.854825,0.050491,126.366087,0.808544,30.261905,7

In [13]:
df.shape

(2973, 14)

In [14]:
df.columns

Index(['mode', 'genres', 'acousticness', 'danceability', 'duration_ms',
       'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness',
       'tempo', 'valence', 'popularity', 'key'],
      dtype='object')

In [15]:
df.dtypes

mode                  int64
genres               object
acousticness        float64
danceability        float64
duration_ms         float64
energy              float64
instrumentalness    float64
liveness            float64
loudness            float64
speechiness         float64
tempo               float64
valence             float64
popularity          float64
key                   int64
dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2973 entries, 0 to 2972
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mode              2973 non-null   int64
 1   genres            2973 non-null   object
 2   acousticness      2973 non-null   float64
 3   danceability      2973 non-null   float64
 4   duration_ms       2973 non-null   float64
 5   energy            2973 non-null   float64
 6   instrumentalness  2973 non-null   float64
 7   liveness          2973 non-null   float64
 8   loudness          2973 non-null   float64
 9   speechiness       2973 non-null   float64
 10  tempo             2973 non-null   float64
 11  valence           2973 non-null   float64
 12  popularity        2973 non-null   float64
 13  key               2973 non-null   int64
dtypes: float64(11), int64(2), object(1)
memory usage: 325.3+ KB

In [17]:
df.describe()

,mode,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
count,2973.000000,2973.000000,2973.000000,2.973000e+03,2973.000000,2973.000000,2973.000000,2973.000000,2973.000000,2973.000000,2973.000000,2973.000000,2973.000000
mean,0.833165,0.401241,0.537187,2.517209e+05,0.561143,0.211366,0.192800,-10.509848,0.083588,119.018723,0.492748,39.919185,5.938782
std,0.372891,0.319760,0.150668,9.465686e+04,0.234486,0.267329,0.092356,5.369202,0.080483,17.469188,0.201820,16.748723,3.368110
min,0.000000,0.000003,0.056900,3.094600e+04,0.001002,0.000000,0.022200,-41.825000,0.023800,47.135722,0.003353,0.000000,0.000000
25%,1.000000,0.119050,0.441202,2.063788e+05,0.395058,0.004835,0.137687,-12.427656,0.044900,109.198143,0.348578,32.491279,3.000000
50%,1.000000,0.321745,0.546496,2.375453e+05,0.601195,0.080700,0.178764,-9.221817,0.059457,119.194167,0.500048,43.056569,7.000000
75%,1.000000,0.673991,0.647500,2.772720e+05,0.730127,0.343333,0.220856,-6.920125,0.091000,127.508750,0.640257,51.138889,9.000000
max,1.000000,0.996000,0.929000,2.382587e+06,0.994667,0.992000,0.960000,0.060000,0.946219,204.212000,0.980000,80.666667,11.000000

In [18]:
df.isnull().sum()

mode                0
genres              0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
key                 0
dtype: int64

In [19]:
df.isnull().sum().sum()

np.int64(0)

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df["genres"].unique()

array(['21st century classical', '432hz', '8-bit', ..., 'zouk',
       'zurich indie', 'zydeco'], shape=(2973,), dtype=object)

In [22]:
df.sample(5)

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
1499,1,japanese folk,0.413568,0.612448,233489.041667,0.644948,0.227999,0.183129,-7.721083,0.068490,122.218979,0.582062,36.229167,2
2246,1,protopunk,0.210470,0.483379,207304.320070,0.688208,0.106215,0.201295,-9.414603,0.065043,129.732188,0.624713,32.346148,9
26,1,african rock,0.139857,0.668896,236075.312500,0.611063,0.093796,0.149694,-9.361750,0.072654,115.709312,0.606458,42.270833,8
2874,1,vintage chanson,0.935867,0.558861,184086.638888,0.238253,0.044011,0.193059,-14.692632,0.130449,109.481757,0.582765,1.968960,7
2239,1,progressive rock,0.280403,0.415174,347645.446337,0.553670,0.207550,0.203653,-11.532534,0.058282,121.377257,0.424903,35.670780,2

In [23]:
df["energy"]

0       0.071317
1       0.450678
2       0.818000
3       0.419146
4       0.316434
          ...
2968    0.610240
2969    0.909000
2970    0.622444
2971    0.172667
2972    0.609369
Name: energy, Length: 2973, dtype: float64

In [24]:
df[["genres","popularity","energy"]]

                      genres  popularity    energy
0     21st century classical   27.833333  0.071317
1                      432hz   52.500000  0.450678
2                      8-bit   48.000000  0.818000
3                         []   20.859882  0.419146
4                 a cappella   45.820071  0.316434
...                      ...         ...       ...
2968                    zolo   33.778943  0.610240
2969                 zouglou   58.000000  0.909000
2970                    zouk   46.666667  0.622444
2971            zurich indie    0.000000  0.172667
2972                  zydeco   30.261905  0.609369

[2973 rows x 3 columns]

In [25]:
np.max(df["energy"])

np.float64(0.9946666666666668)

In [26]:
np.min(df["energy"])

np.float64(0.0010015)

In [27]:
np.mean(df["tempo"])

np.float64(119.01872257720557)

In [28]:
np.median(df["tempo"])

np.float64(119.19416666666666)

In [29]:
np.std(df["tempo"])

np.float64(17.466249633172414)

In [30]:
np.var(df["tempo"])

np.float64(305.06987624829543)

In [31]:
np.sum(df["popularity"])

np.float64(118679.73584467222)

In [32]:
df.sort_values(by="popularity", ascending=False)

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
237,1,basshall,0.213167,0.818000,169799.166667,0.630167,0.000020,0.081067,-6.627833,0.134833,115.092500,0.588667,80.666667,2
2755,1,trap venezolano,0.044600,0.877000,231848.000000,0.777000,0.000035,0.086300,-4.246000,0.117000,102.020000,0.706000,80.000000,1
2533,1,south african house,0.043833,0.847000,311854.333333,0.562333,0.130339,0.075133,-7.719000,0.050733,123.676333,0.834333,80.000000,1
2778,0,turkish edm,0.008290,0.698000,186700.000000,0.719000,0.000004,0.326000,-4.923000,0.045500,120.062000,0.364000,80.000000,0
46,0,alberta hip hop,0.330000,0.885000,144000.000000,0.685000,0.000000,0.148000,-6.429000,0.062700,99.954000,0.937000,78.500000,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1054,1,folclore navarra,0.930000,0.419000,186440.000000,0.183000,0.000006,0.040000,-14.964000,0.049600,95.067000,0.484000,0.000000,9
2964,0,zambian pop,0.473000,0.689000,42813.000000,0.775000,0.000000,0.219000,-11.938000,0.219000,130.223000,0.646000,0.000000,1
2953,1,xtra raw,0.005500,0.467000,230500.000000,0.988000,0.000000,0.126000,-2.344000,0.427000,154.962000,0.086000,0.000000,1
44,1,albany ny indie,0.000564,0.852000,215427.000000,0.251000,0.756000,0.095700,-13.225000,0.068300,141.759000,0.186000,0.000000,8
2971,0,zurich indie,0.993000,0.705667,198417.333333,0.172667,0.468633,0.179667,-11.453333,0.348667,91.278000,0.739000,0.000000,7

In [34]:
s=[1,2,3,4,5]
s[::-1]

[5, 4, 3, 2, 1]

In [35]:
#axis=0 → Column-wise (Top → Bottom)
#axis=1 → Row-wise (Left → Right
arr=df["duration_ms"]
np.mean(arr, axis=0)

np.float64(251720.8545979002)

In [36]:
np.max(arr, axis=0)

np.float64(2382586.666666666)

In [37]:
np.min(arr, axis=0)

np.float64(30946.0)

In [38]:
np.std(arr, axis=0)

np.float64(94640.93530948344)

In [39]:
np.var(arr, axis=0)

np.float64(8956906636.253828)

In [40]:
np.sum(arr, axis=0)

np.float64(748366100.7195573)

In [42]:
np.argmax(df["popularity"])

np.int64(237)

In [43]:
np.argmin(df["energy"])

np.int64(283)

In [44]:
np.unique(df["key"])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.percentile(df["tempo"], 50)

np.float64(119.19416666666666)

In [46]:
df[df["popularity"] > 80]

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
237,1,basshall,0.213167,0.818,169799.166667,0.630167,0.00002,0.081067,-6.627833,0.134833,115.0925,0.588667,80.666667,2

In [47]:
a=df.loc[1:10,"popularity"]
a

1     52.500000
2     48.000000
3     20.859882
4     45.820071
5     43.500000
6     58.933333
7     39.790702
8     39.000000
9     21.937500
10    46.638462
Name: popularity, dtype: float64

In [49]:
df.groupby("genres")
df.groupby("genres")["popularity"].mean()

genres
21st century classical    27.833333
432hz                     52.500000
8-bit                     48.000000
[]                        20.859882
a cappella                45.820071
                            ...
zolo                      33.778943
zouglou                   58.000000
zouk                      46.666667
zurich indie               0.000000
zydeco                    30.261905
Name: popularity, Length: 2973, dtype: float64

In [50]:
df.isnull()

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2969,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2970,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2971,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2972,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [51]:
df.isnull().sum()

mode                0
genres              0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
popularity          0
key                 0
dtype: int64

In [52]:
df.notnull()

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2969,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2970,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2971,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2972,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [53]:
df.fillna(0)

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968,1,zolo,0.222625,0.547082,2.580991e+05,0.610240,0.143872,0.204206,-11.295878,0.061088,125.494919,0.596155,33.778943,9
2969,0,zouglou,0.161000,0.863000,2.063200e+05,0.909000,0.000000,0.108000,-5.985000,0.081300,119.038000,0.845000,58.000000,7
2970,1,zouk,0.263261,0.748889,3.060728e+05,0.622444,0.257227,0.089678,-10.289222,0.038778,101.965222,0.824111,46.666667,5
2971,0,zurich indie,0.993000,0.705667,1.984173e+05,0.172667,0.468633,0.179667,-11.453333,0.348667,91.278000,0.739000,0.000000,7
2972,1,zydeco,0.421038,0.629409,1.716717e+05,0.609369,0.019248,0.255877,-9.854825,0.050491,126.366087,0.808544,30.261905,7

In [55]:
ff = df["tempo"].fillna(df["tempo"].mean())
ff

0        75.336500
1       120.285667
2       133.444000
3       112.857352
4       112.110362
           ...
2968    125.494919
2969    119.038000
2970    101.965222
2971     91.278000
2972    126.366087
Name: tempo, Length: 2973, dtype: float64

In [56]:
df.fillna(method="ffill")

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_3560\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968,1,zolo,0.222625,0.547082,2.580991e+05,0.610240,0.143872,0.204206,-11.295878,0.061088,125.494919,0.596155,33.778943,9
2969,0,zouglou,0.161000,0.863000,2.063200e+05,0.909000,0.000000,0.108000,-5.985000,0.081300,119.038000,0.845000,58.000000,7
2970,1,zouk,0.263261,0.748889,3.060728e+05,0.622444,0.257227,0.089678,-10.289222,0.038778,101.965222,0.824111,46.666667,5
2971,0,zurich indie,0.993000,0.705667,1.984173e+05,0.172667,0.468633,0.179667,-11.453333,0.348667,91.278000,0.739000,0.000000,7
2972,1,zydeco,0.421038,0.629409,1.716717e+05,0.609369,0.019248,0.255877,-9.854825,0.050491,126.366087,0.808544,30.261905,7

In [57]:
df.fillna(method="bfill")

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_3560\3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968,1,zolo,0.222625,0.547082,2.580991e+05,0.610240,0.143872,0.204206,-11.295878,0.061088,125.494919,0.596155,33.778943,9
2969,0,zouglou,0.161000,0.863000,2.063200e+05,0.909000,0.000000,0.108000,-5.985000,0.081300,119.038000,0.845000,58.000000,7
2970,1,zouk,0.263261,0.748889,3.060728e+05,0.622444,0.257227,0.089678,-10.289222,0.038778,101.965222,0.824111,46.666667,5
2971,0,zurich indie,0.993000,0.705667,1.984173e+05,0.172667,0.468633,0.179667,-11.453333,0.348667,91.278000,0.739000,0.000000,7
2972,1,zydeco,0.421038,0.629409,1.716717e+05,0.609369,0.019248,0.255877,-9.854825,0.050491,126.366087,0.808544,30.261905,7

In [ ]:
df.dropna()#removes rows

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968,1,zolo,0.222625,0.547082,2.580991e+05,0.610240,0.143872,0.204206,-11.295878,0.061088,125.494919,0.596155,33.778943,9
2969,0,zouglou,0.161000,0.863000,2.063200e+05,0.909000,0.000000,0.108000,-5.985000,0.081300,119.038000,0.845000,58.000000,7
2970,1,zouk,0.263261,0.748889,3.060728e+05,0.622444,0.257227,0.089678,-10.289222,0.038778,101.965222,0.824111,46.666667,5
2971,0,zurich indie,0.993000,0.705667,1.984173e+05,0.172667,0.468633,0.179667,-11.453333,0.348667,91.278000,0.739000,0.000000,7
2972,1,zydeco,0.421038,0.629409,1.716717e+05,0.609369,0.019248,0.255877,-9.854825,0.050491,126.366087,0.808544,30.261905,7

In [59]:
df.dropna(axis=1)

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968,1,zolo,0.222625,0.547082,2.580991e+05,0.610240,0.143872,0.204206,-11.295878,0.061088,125.494919,0.596155,33.778943,9
2969,0,zouglou,0.161000,0.863000,2.063200e+05,0.909000,0.000000,0.108000,-5.985000,0.081300,119.038000,0.845000,58.000000,7
2970,1,zouk,0.263261,0.748889,3.060728e+05,0.622444,0.257227,0.089678,-10.289222,0.038778,101.965222,0.824111,46.666667,5
2971,0,zurich indie,0.993000,0.705667,1.984173e+05,0.172667,0.468633,0.179667,-11.453333,0.348667,91.278000,0.739000,0.000000,7
2972,1,zydeco,0.421038,0.629409,1.716717e+05,0.609369,0.019248,0.255877,-9.854825,0.050491,126.366087,0.808544,30.261905,7